### ISSUE TITLE
主催者未入力のイベントを読み込んだ時にDiscordで特定条件のユーザがメンションされる

### ISSUE THREAD

**Issue by nacco-bron** [infra-workshop/iw_discord_bot#2]
主催者未入力のイベントを読み込んだ時にDiscordで特定条件のユーザがメンションされる。

事象が確認されたイベント
- 0721-ほにゃららｌｔリレー　２nd
- 0718-【ゆるっと】インターネットへのつなげ方入門

**Comment by 0Delta** [comment]
826c363574782d540bac96fa11def7b7695bf8ae
修正しました。
